/**
 * 
 */
package fr.emac.gipsi.gsi.ecran;

import fr.emac.gipsi.gsi.screen.Screen;
import fr.emac.gipsi.gsi.screen.VisualRectangle;

/**
 * @author Truptil Sebastien - sebastien.truptil@gmail.com
 *
 */
public class ListScreen {

	public static Screen first(){
		Screen first = new Screen("first");
		first.setColMax(8);
		first.setLigMax(8);
		first.getRectangles().add(new VisualRectangle(0,0,"Cyan"));
		first.getRectangles().add(new VisualRectangle(0,1,"Black"));
		first.getRectangles().add(new VisualRectangle(0,2,"Cyan"));
		first.getRectangles().add(new VisualRectangle(0,3,"Black"));
		first.getRectangles().add(new VisualRectangle(0,4,"Cyan"));
		first.getRectangles().add(new VisualRectangle(0,5,"Black"));
		first.getRectangles().add(new VisualRectangle(0,6,"Cyan"));
		first.getRectangles().add(new VisualRectangle(0,7,"Black"));
		first.getRectangles().add(new VisualRectangle(0,8,"Cyan"));
		first.getRectangles().add(new VisualRectangle(1,0,"Cyan"));
		first.getRectangles().add(new VisualRectangle(1,1,"Cyan"));
		first.getRectangles().add(new VisualRectangle(1,2,"Cyan"));
		first.getRectangles().add(new VisualRectangle(1,3,"Cyan"));
		first.getRectangles().add(new VisualRectangle(1,4,"Cyan"));
		first.getRectangles().add(new VisualRectangle(1,5,"Cyan"));
		first.getRectangles().add(new VisualRectangle(1,6,"Cyan"));
		first.getRectangles().add(new VisualRectangle(1,7,"Cyan"));
		first.getRectangles().add(new VisualRectangle(1,8,"Cyan"));
		first.getRectangles().add(new VisualRectangle(2,0,"Cyan"));
		first.getRectangles().add(new VisualRectangle(2,1,"Cyan"));
		first.getRectangles().add(new VisualRectangle(2,2,"Magenta"));
		first.getRectangles().add(new VisualRectangle(2,3,"Magenta"));
		first.getRectangles().add(new VisualRectangle(2,4,"Cyan"));
		first.getRectangles().add(new VisualRectangle(2,5,"Magenta"));
		first.getRectangles().add(new VisualRectangle(2,6,"Magenta"));
		first.getRectangles().add(new VisualRectangle(2,7,"Cyan"));
		first.getRectangles().add(new VisualRectangle(2,8,"Cyan"));
		first.getRectangles().add(new VisualRectangle(3,0,"Cyan"));
		first.getRectangles().add(new VisualRectangle(3,1,"Cyan"));
		first.getRectangles().add(new VisualRectangle(3,2,"Magenta"));
		first.getRectangles().add(new VisualRectangle(3,3,"Magenta"));
		first.getRectangles().add(new VisualRectangle(3,4,"Cyan"));
		first.getRectangles().add(new VisualRectangle(3,5,"Magenta"));
		first.getRectangles().add(new VisualRectangle(3,6,"Magenta"));
		first.getRectangles().add(new VisualRectangle(3,7,"Cyan"));
		first.getRectangles().add(new VisualRectangle(3,8,"Cyan"));
		first.getRectangles().add(new VisualRectangle(4,0,"Cyan"));
		first.getRectangles().add(new VisualRectangle(4,1,"Cyan"));
		first.getRectangles().add(new VisualRectangle(4,2,"Cyan"));
		first.getRectangles().add(new VisualRectangle(4,3,"Cyan"));
		first.getRectangles().add(new VisualRectangle(4,4,"Cyan"));
		first.getRectangles().add(new VisualRectangle(4,5,"Cyan"));
		first.getRectangles().add(new VisualRectangle(4,6,"Cyan"));
		first.getRectangles().add(new VisualRectangle(4,7,"Cyan"));
		first.getRectangles().add(new VisualRectangle(4,8,"Cyan"));
		first.getRectangles().add(new VisualRectangle(5,0,"Cyan"));
		first.getRectangles().add(new VisualRectangle(5,1,"Cyan"));
		first.getRectangles().add(new VisualRectangle(5,2,"Cyan"));
		first.getRectangles().add(new VisualRectangle(5,3,"Cyan"));
		first.getRectangles().add(new VisualRectangle(5,4,"Magenta"));
		first.getRectangles().add(new VisualRectangle(5,5,"Cyan"));
		first.getRectangles().add(new VisualRectangle(5,6,"Cyan"));
		first.getRectangles().add(new VisualRectangle(5,7,"Cyan"));
		first.getRectangles().add(new VisualRectangle(5,8,"Cyan"));
		first.getRectangles().add(new VisualRectangle(6,0,"Cyan"));
		first.getRectangles().add(new VisualRectangle(6,1,"Cyan"));
		first.getRectangles().add(new VisualRectangle(6,2,"Cyan"));
		first.getRectangles().add(new VisualRectangle(6,3,"Cyan"));
		first.getRectangles().add(new VisualRectangle(6,4,"Cyan"));
		first.getRectangles().add(new VisualRectangle(6,5,"Cyan"));
		first.getRectangles().add(new VisualRectangle(6,6,"Cyan"));
		first.getRectangles().add(new VisualRectangle(6,7,"Cyan"));
		first.getRectangles().add(new VisualRectangle(6,8,"Cyan"));
		first.getRectangles().add(new VisualRectangle(7,0,"Cyan"));
		first.getRectangles().add(new VisualRectangle(7,1,"Cyan"));
		first.getRectangles().add(new VisualRectangle(7,2,"Magenta"));
		first.getRectangles().add(new VisualRectangle(7,3,"Magenta"));
		first.getRectangles().add(new VisualRectangle(7,4,"Magenta"));
		first.getRectangles().add(new VisualRectangle(7,5,"Magenta"));
		first.getRectangles().add(new VisualRectangle(7,6,"Magenta"));
		first.getRectangles().add(new VisualRectangle(7,7,"Cyan"));
		first.getRectangles().add(new VisualRectangle(7,8,"Cyan"));
		first.getRectangles().add(new VisualRectangle(8,0,"Cyan"));
		first.getRectangles().add(new VisualRectangle(8,1,"Cyan"));
		first.getRectangles().add(new VisualRectangle(8,2,"Cyan"));
		first.getRectangles().add(new VisualRectangle(8,3,"Cyan"));
		first.getRectangles().add(new VisualRectangle(8,4,"Cyan"));
		first.getRectangles().add(new VisualRectangle(8,5,"Cyan"));
		first.getRectangles().add(new VisualRectangle(8,6,"Cyan"));
		first.getRectangles().add(new VisualRectangle(8,7,"Cyan"));
		first.getRectangles().add(new VisualRectangle(8,8,"Cyan"));
		return first;
		}	
	public static Screen second(){
		Screen second = new Screen("second");
		second.setColMax(8);
		second.setLigMax(8);
		second.getRectangles().add(new VisualRectangle(0,0,"LawnGreen"));
		second.getRectangles().add(new VisualRectangle(0,1,"DeepPink"));
		second.getRectangles().add(new VisualRectangle(0,2,"LawnGreen"));
		second.getRectangles().add(new VisualRectangle(0,3,"DeepPink"));
		second.getRectangles().add(new VisualRectangle(0,4,"LawnGreen"));
		second.getRectangles().add(new VisualRectangle(0,5,"DeepPink"));
		second.getRectangles().add(new VisualRectangle(0,6,"LawnGreen"));
		second.getRectangles().add(new VisualRectangle(0,7,"DeepPink"));
		second.getRectangles().add(new VisualRectangle(0,8,"LawnGreen"));
		second.getRectangles().add(new VisualRectangle(1,0,"DeepPink"));
		second.getRectangles().add(new VisualRectangle(1,1,"LawnGreen"));
		second.getRectangles().add(new VisualRectangle(1,2,"DeepPink"));
		second.getRectangles().add(new VisualRectangle(1,3,"LawnGreen"));
		second.getRectangles().add(new VisualRectangle(1,4,"DeepPink"));
		second.getRectangles().add(new VisualRectangle(1,5,"LawnGreen"));
		second.getRectangles().add(new VisualRectangle(1,6,"DeepPink"));
		second.getRectangles().add(new VisualRectangle(1,7,"LawnGreen"));
		second.getRectangles().add(new VisualRectangle(1,8,"DeepPink"));
		second.getRectangles().add(new VisualRectangle(2,0,"LawnGreen"));
		second.getRectangles().add(new VisualRectangle(2,1,"DeepPink"));
		second.getRectangles().add(new VisualRectangle(2,2,"LawnGreen"));
		second.getRectangles().add(new VisualRectangle(2,3,"DeepPink"));
		second.getRectangles().add(new VisualRectangle(2,4,"LawnGreen"));
		second.getRectangles().add(new VisualRectangle(2,5,"DeepPink"));
		second.getRectangles().add(new VisualRectangle(2,6,"LawnGreen"));
		second.getRectangles().add(new VisualRectangle(2,7,"DeepPink"));
		second.getRectangles().add(new VisualRectangle(2,8,"LawnGreen"));
		second.getRectangles().add(new VisualRectangle(3,0,"DeepPink"));
		second.getRectangles().add(new VisualRectangle(3,1,"LawnGreen"));
		second.getRectangles().add(new VisualRectangle(3,2,"DeepPink"));
		second.getRectangles().add(new VisualRectangle(3,3,"LawnGreen"));
		second.getRectangles().add(new VisualRectangle(3,4,"DeepPink"));
		second.getRectangles().add(new VisualRectangle(3,5,"LawnGreen"));
		second.getRectangles().add(new VisualRectangle(3,6,"DeepPink"));
		second.getRectangles().add(new VisualRectangle(3,7,"LawnGreen"));
		second.getRectangles().add(new VisualRectangle(3,8,"DeepPink"));
		second.getRectangles().add(new VisualRectangle(4,0,"LawnGreen"));
		second.getRectangles().add(new VisualRectangle(4,1,"DeepPink"));
		second.getRectangles().add(new VisualRectangle(4,2,"LawnGreen"));
		second.getRectangles().add(new VisualRectangle(4,3,"DeepPink"));
		second.getRectangles().add(new VisualRectangle(4,4,"LawnGreen"));
		second.getRectangles().add(new VisualRectangle(4,5,"DeepPink"));
		second.getRectangles().add(new VisualRectangle(4,6,"LawnGreen"));
		second.getRectangles().add(new VisualRectangle(4,7,"DeepPink"));
		second.getRectangles().add(new VisualRectangle(4,8,"LawnGreen"));
		second.getRectangles().add(new VisualRectangle(5,0,"DeepPink"));
		second.getRectangles().add(new VisualRectangle(5,1,"LawnGreen"));
		second.getRectangles().add(new VisualRectangle(5,2,"DeepPink"));
		second.getRectangles().add(new VisualRectangle(5,3,"LawnGreen"));
		second.getRectangles().add(new VisualRectangle(5,4,"DeepPink"));
		second.getRectangles().add(new VisualRectangle(5,5,"LawnGreen"));
		second.getRectangles().add(new VisualRectangle(5,6,"DeepPink"));
		second.getRectangles().add(new VisualRectangle(5,7,"LawnGreen"));
		second.getRectangles().add(new VisualRectangle(5,8,"DeepPink"));
		second.getRectangles().add(new VisualRectangle(6,0,"LawnGreen"));
		second.getRectangles().add(new VisualRectangle(6,1,"DeepPink"));
		second.getRectangles().add(new VisualRectangle(6,2,"LawnGreen"));
		second.getRectangles().add(new VisualRectangle(6,3,"DeepPink"));
		second.getRectangles().add(new VisualRectangle(6,4,"LawnGreen"));
		second.getRectangles().add(new VisualRectangle(6,5,"DeepPink"));
		second.getRectangles().add(new VisualRectangle(6,6,"LawnGreen"));
		second.getRectangles().add(new VisualRectangle(6,7,"DeepPink"));
		second.getRectangles().add(new VisualRectangle(6,8,"LawnGreen"));
		second.getRectangles().add(new VisualRectangle(7,0,"DeepPink"));
		second.getRectangles().add(new VisualRectangle(7,1,"LawnGreen"));
		second.getRectangles().add(new VisualRectangle(7,2,"DeepPink"));
		second.getRectangles().add(new VisualRectangle(7,3,"LawnGreen"));
		second.getRectangles().add(new VisualRectangle(7,4,"DeepPink"));
		second.getRectangles().add(new VisualRectangle(7,5,"LawnGreen"));
		second.getRectangles().add(new VisualRectangle(7,6,"DeepPink"));
		second.getRectangles().add(new VisualRectangle(7,7,"LawnGreen"));
		second.getRectangles().add(new VisualRectangle(7,8,"DeepPink"));
		second.getRectangles().add(new VisualRectangle(8,0,"LawnGreen"));
		second.getRectangles().add(new VisualRectangle(8,1,"DeepPink"));
		second.getRectangles().add(new VisualRectangle(8,2,"LawnGreen"));
		second.getRectangles().add(new VisualRectangle(8,3,"DeepPink"));
		second.getRectangles().add(new VisualRectangle(8,4,"LawnGreen"));
		second.getRectangles().add(new VisualRectangle(8,5,"DeepPink"));
		second.getRectangles().add(new VisualRectangle(8,6,"LawnGreen"));
		second.getRectangles().add(new VisualRectangle(8,7,"DeepPink"));
		second.getRectangles().add(new VisualRectangle(8,8,"LawnGreen"));
		return second;
		}
}
